name: githubactions

on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repository
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven

            - name: Build Project
              run: mvn clean install -DskipTests

            - name: Run SonarQube Scan
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: 'https://sonarcloud.io'
              run: |
               mvn clean verify sonar:sonar \
               -Dsonar.host.url=$SONAR_HOST_URL \
               -Dsonar.login=$SONAR_TOKEN \
               -Dsonar.organization=mounika257 \
               -Dsonar.projectKey=mounika257-1
