name: githubactions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: clone
              uses: actions/checkout@v4
            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                java-version: '11'
                distribution: 'temurin'
                cache: maven
            - name: build
              run: mvn clean install
    sonar:
        name: SonarQube Analysis
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'
            
            - name: Run SonarQube Scan
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: 'https://sonarcloud.io'
              run: |
               mvn sonar:sonar \
               -Dsonar.host.url=$SONAR_HOST_URL \
               -Dsonar.login=$SONAR_TOKEN
               -Dsonar.organization=mounika257-1 \
               -Dsonar.projectKey=mounika257_Ekart
              
